security:
    firewalls:
        secured_area:
            pattern:    ^/
            anonymous: ~
            form_login:
                login_path:  /login
                check_path:  /login_check
            logout:
                path:   /logout
                target: /

    providers:
        users:
            entity: { class: AppBundle:User, property: username }

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
#        - { path: ^/profile, roles: ROLE_USER }

    encoders:
        AppBundle\Entity\User:
            algorithm: sha512