<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MovieRepository extends EntityRepository
{
    public function countAll(){
        $query = $this->createQueryBuilder("m")
                ->select("COUNT(m)")
                ->getQuery();
                $count = $query->getSingleScalarResult();
                return $count;
    }
}
